spring:
  dataSource:
    diriver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atithih
    username: root
    password: root

    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MysqlDialect
        open-in-view: false
        generate-ddl: true

